
name: dockerfile

on:
  workflow_call:
    inputs:
      registry:
        required: false
        type: string
        default: docker.io
      platforms:
        required: false
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: false
      IMAGE_NAME:
        required: false
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true

jobs:
  dockerfile:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v4
      -
        name: image-name
        if: ${{ env.IMAGE_NAME != '' }}
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
        run: |
          echo "IMAGE_NAME=${{ inputs.registry }}/${{ env.IMAGE_NAME }}" >> $GITHUB_ENV
      -
        name: image-name-default
        if: ${{ env.IMAGE_NAME == '' }}
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
        run: |
          echo "IMAGE_NAME=${{ inputs.registry }}/${{ secrets.REGISTRY_USERNAME }}/${{ github.event.repository.name }}" >> $GITHUB_ENV

      -
        name: buildx
        uses: docker/setup-buildx-action@v4
      -
        name: login
        uses: docker/login-action@v4
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: build-push
        uses: docker/build-push-action@v5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          context: .
          push: true
          platforms: ${{ inputs.platforms }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max
